### ISSUE TITLE
功能增强：自动更新脚本

### ISSUE THREAD

**Issue by uwang** [suixing8/115-strm#12]
1. 手动脚本支持 update_existing 和 delete_absent 选项。生成的自动更新脚本还不支持两个选项
2. 自动更新脚本增加从配置文件读取配置项

**Comment by suixing8** [comment]
我这个脚本用ai写的，现在没时间去维护，如果你会也可以更新上去，这个应是不难的

**Comment by uwang** [comment]
优化 pr #14

**Comment by uwang** [comment]
已经整合进去了。

推荐使用 docker 镜像版，可以自定义是否更新已存在的 strm，和是否删除目录树中不存在的 strm
