### ISSUE TITLE
为什么生成的strm文件多了一个“/”？

### ISSUE THREAD

**Issue by Swiftfrog** [suixing8/115-strm#2]
用脚本生成的strm文件内容如下：

http://alist:5244/d/fe/media//movie.1970s/Nezha.Conquers.the.Dragon.King.1979.1080p.BluRay.REMUX.AVC.FLAC1.0-RO%5BPianYuan%5D/Nezha.Conquers.the.Dragon.King.1979.1080p.BluRay.REMUX.AVC.FLAC1.0-RO.mkv

日志如下：
请输入alist的地址+端口（例如：http://abc.com:5244）：
http://alist:5244
请输入alist存储里对应的挂载路径信息：
fe/media/
请输入剔除选项（输入要剔除的目录层级数量，默认为2）：
2
总文件：1522，剔除数：2，有效数：1520，已处理：1520，进度：100.00%，耗时：00:00
已完成 .strm 文件生成。

**Comment by Swiftfrog** [comment]
对应挂载路径和目录地址拼接的地方多了一个“/”。

**Comment by suixing8** [comment]
刚发现这个问题，我这边测试不影响使用，稍后修复一下代码，

**Comment by suixing8** [comment]
fe/media/

这个路径也不是这样子填写的，是你alist储存里面挂载的路劲，可以看一下教程

**Comment by Swiftfrog** [comment]
剔除选项（输入要剔除的目录层级数量，默认为2）

搞定了，我目录层级是1，这个的关系，非常感谢。

**Comment by Swiftfrog** [comment]
测试如下：
请选择操作：
1: 将目录树转换为目录文件
2: 生成 .strm 文件
3: 建立alist索引数据库
4: 高级配置（处理非常见媒体文件时使用）
0: 退出
2
找到以下目录文件，请选择：
1) test.txt.converted_目录文件.txt
2) 输入完整路径
#? 1
请输入 .strm 文件保存的路径：
./ml
请输入alist的地址+端口（例如：http://abc.com:5244）：
http://alist:5244/
请输入alist存储里对应的挂载路径信息：
/fe/media/

strm结果：
http://alist:5244/d/fe/mediaMovie/movie.1970s/Nezha.Conquers.the.Dragon.King.1979.1080p.BluRay.REMUX.AVC.FLAC1.0-RO%5BPianYuan%5D/Nezha.Conquers.the.Dragon.King.1979.1080p.BluRay.REMUX.AVC.FLAC1.0-RO.mkv
**media和Movie之间少了1个/。**


请选择操作：
1: 将目录树转换为目录文件
2: 生成 .strm 文件
3: 建立alist索引数据库
4: 高级配置（处理非常见媒体文件时使用）
0: 退出
2
找到以下目录文件，请选择：
1) test.txt.converted_目录文件.txt
2) 输入完整路径
#? 1
请输入 .strm 文件保存的路径：
./ml
请输入alist的地址+端口（例如：http://abc.com:5244）：
http://10.8.0.18:5244/
请输入alist存储里对应的挂载路径信息：
/fe/media
请输入剔除选项（输入要剔除的目录层级数量，默认为2）：
1
总文件：1522，剔除数：1，有效数：1521，已处理：1521，进度：100.00%，耗时：00:00
已完成 .strm 文件生成。

结果：
http://alist:5244/d/fe/mediaMovie/movie.1970s/Nezha.Conquers.the.Dragon.King.1979.1080p.BluRay.REMUX.AVC.FLAC1.0-RO%5BPianYuan%5D/Nezha.Conquers.the.Dragon.King.1979.1080p.BluRay.REMUX.AVC.FLAC1.0-RO.mkv

**media和Movie之间少了1个/。**

是不是
**alist_url="${alist_url%/}/d/${mount_path}"**
是对的？

**Comment by Swiftfrog** [comment]
**前一个版本测试如下：**

找到以下目录文件，请选择：
1) test.txt.converted_目录文件.txt
2) 输入完整路径
#? 1
请输入 .strm 文件保存的路径：
./ml
请输入alist的地址+端口（例如：http://abc.com:5244）：
**http://alist:5244/**
请输入alist存储里对应的挂载路径信息：
**/fe/media**
请输入剔除选项（输入要剔除的目录层级数量，默认为2）：
1
**输出结果对的。**

---

找到以下目录文件，请选择：
1) test.txt.converted_目录文件.txt
2) 输入完整路径
#? 1
请输入 .strm 文件保存的路径：
./ml
请输入alist的地址+端口（例如：http://abc.com:5244）：
**http://alist:5244**
请输入alist存储里对应的挂载路径信息：
**/fe/media**
请输入剔除选项（输入要剔除的目录层级数量，默认为2）：
1
**输出结果对的。**

---

找到以下目录文件，请选择：
1) test.txt.converted_目录文件.txt
2) 输入完整路径
#? 1
请输入 .strm 文件保存的路径：
./ml
请输入alist的地址+端口（例如：http://abc.com:5244）：
**http://alist:5244**
请输入alist存储里对应的挂载路径信息：
**fe/media**
请输入剔除选项（输入要剔除的目录层级数量，默认为2）：
1
**输出结果对的。**

**Comment by Swiftfrog** [comment]
我可能前面的多了一个“/“的测试误导你了，抱歉。

**Comment by suixing8** [comment]
好的，没事，我再测试一下，因为会涉及到有些挂载的是根目录/，我也希望程序在用户输入错误的时候自动为用户进行补齐或者去除/，比如fe/media/，这种是错误的，前面缺少/，后面多了/，因为正常情况下，处理好的目录树文件，即使剔除路径后，路劲开始也会带/，所以插入的路劲最后是不需要/的，从你的反馈来看，是在插入路劲和目录树路劲合并的时候有问题

**Comment by yndzm** [comment]
iso生成的strm文件kodi不能播放
