### ISSUE TITLE
目录层级为0时，第一级目录会乱码。

### ISSUE THREAD

**Issue by Swiftfrog** [suixing8/115-strm#3]
原始的目录树txt文件的第一级为：|——media

转为目录文件后，第一级为：/|——media

“|——“没有被转义掉。

故目录层级为0时，第一目录就乱码了，strm文件在第一级有乱码出现。

**Comment by suixing8** [comment]
因为使用导出的115目录，挂载到alist后，是不需要第一行的|——media目录的，这个是属于挂载目录的上一级目录，比如115目录/bbb/ccc/ddd，挂载的是/ccc目录，挂载到alist储存路劲/aaa，那alist路劲就是/aaa/ddd，跟115一级路劲/bbb没关系，给我感觉使用场景不高，所以写脚本的时候没考虑过这个问题，你可以选择在alist挂载目录多加一层目录，比如上面的例子中，你可以选择挂载到alist储存路劲/bbb/ccc，那alist路劲就是/bbb/ccc/ddd，就可以解决这个问题

**Comment by Swiftfrog** [comment]
好的，谢谢。我自己用sed在你的sh上修改了一下，再次感谢。

**Comment by suixing8** [comment]
不客气，最新的脚本没有其他问题了吧，我没有进行详细的，各种可能存在的问题下测试，

**Comment by Swiftfrog** [comment]
暂时没有，我明天测试一下数据库。
