### ISSUE TITLE
为什么要添加类似pdf,txt,jpg这类的strm？

### ISSUE THREAD

**Issue by Swiftfrog** [suixing8/115-strm#6]
media_extensions = {
        'mp3', 'flac', 'wav', 'aac', 'ogg', 'wma', 'alac', 'm4a',
        'aiff', 'ape', 'dsf', 'dff', 'wv', 'pcm', 'tta',
        'mp4', 'mkv', 'avi', 'mov', 'wmv', 'flv', 'webm', 'vob', 'mpg', 'mpeg',
        'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'svg', 'heic',
        'iso', 'img', 'bin', 'nrg', 'cue', 'dvd',
        'lrc', 'srt', 'sub', 'ssa', 'ass', 'vtt', 'txt',
        'pdf', 'doc', 'docx', 'csv', 'xml', 'new'
    }

这些看不明白啊。。。图片，文件生成strm，似乎没什么用啊！

如果是给数据库用，那么执行生成strm文件的时候，非媒体格式应该去掉的啊。

---

如果目录树如下：
|——根目录
| |-Test
| | |-系列.怒火攻心.Crank.2006-2009.1080p
| | | |-Crank.2006.DC.Ger.BluRay.1080p.DTS-HD.HR.5.1.x264-beAst.mkv
| | | |-Crank.High.Voltage.2009.BluRay.1080p.DTS-HD.MA.7.1.x264-beAst.mkv
| | | |-Media20241201153900_目录树.txt
也就是生产目录树之前，目录下有txt文件。

那么脚本也会生产txt的strm文件，但是txt文件生产strm没用啊。

**Comment by suixing8** [comment]
因为和alist输入库共用的文件格式，解决方法：
以下会显示所有的strm文件格式，
find . -type f -name "*.strm" | awk -F. 'NF>2 {print $(NF-1)}' | sort -u
以下删除指定的文件格式的strm文件，示例png txt自行修改
sudo bash -c 'find . -type f -name "*.strm" | while read -r file; do
    base_name="${file%.strm}"
    ext="${base_name##*.}"
    if [[ " png txt " =~ " ${ext} " ]]; then
        rm "$file"
        echo "Deleted: $file"
    fi
done'

**Comment by Swiftfrog** [comment]
好的，谢谢。我修改了一下脚本，直接去掉了无关的文件格式。

**Comment by uwang** [comment]
调整了下脚本

```bash
bash -c 'find . -type f -name "*.strm" | while read -r file; do
base_name="${file%.strm}"
ext="${base_name##*.}"
if [[ " png txt jpg jpeg xml ass ssa srt" =~ " ${ext} " ]]; then
rm "$file"
echo "Deleted: $file"
fi
done'
```
